-- CREATE TABLE view_agents (AgentId UInt64, AgentName String, Online UInt8, OSInfo String, MachineGroup String) ENGINE=URL('http://kaseya-proxy:8090/api/v1.0/assetmgmt/agents?accept=jsonl', JSONEachRow) SETTINGS input_format_skip_unknown_fields=1;
-- CREATE TABLE view_patch_history (AgentId UInt64, UpdateTitle String, PatchState UInt8) ENGINE=URL('http://kaseya-proxy:8090/assetmgmt/patch/history?accept=jsonl', JSONEachRow) SETTINGS input_format_skip_unknown_fields=1;
-- drop table agents;
-- drop table pathHistory;